uses argparse to read in values from commandline.
standupmaths/rolling_shutter pull request #2
Opened 2017-07-13 02:43 UTC by basheersubei

figured I'd make an improved version of #1 to demonstrate [argparse](https://docs.python.org/2/library/argparse.html)

2017-07-13 02:46 UTC, basheersubei commented
fair warning: I haven't tested this on a set of images (would be great if someone could post a small set : )

2017-07-13 03:23 UTC, heyitswither commented
+1

2017-07-13 04:32 UTC, arguiot commented
+1

2017-07-13 05:42 UTC, RoelAdriaans requested changes

2017-07-13 05:42 UTC, RoelAdriaans-B-informed commented on rollingshutter.py
> +    parser.add_argument('-x', '--extension-type', default='png', help='Speed variable to control how many rows to jump by per frame.')
The help for the extention type is the same as for the speed

2017-07-13 05:47 UTC, RoelAdriaans-B-informed commented on rollingshutter.py
> +    parser.add_argument('-i', '--input_directory', required=True, help='Path to directory containing input images.')
Maybe do not use named arguments, but positional. 
Most linux utils, like cp, ls,... use those for filenames. 

Then you can do rollingshutter.py in/ out/, makes is a bit cleaner on the console?

2017-07-13 07:06 UTC, colcomb commented on rollingshutter.py
> +    for filename in glob.glob(os.path.join(input_directory, "*.", extension_type)):
`os.path.join(input_directory, "*.", extension_type)` adds a slash between the files and the extension.
Should be `os.path.join(input_directory, "*." + extension_type)`.

2017-07-14 02:46 UTC, basheersubei commented on rollingshutter.py
> +    for filename in glob.glob(os.path.join(input_directory, "*.", extension_type)):
d'oh! Nice catch!

2017-07-14 02:48 UTC, basheersubei commented on rollingshutter.py
> +    parser.add_argument('-i', '--input_directory', required=True, help='Path to directory containing input images.')
I dunno, "explicit is better than implicit" is usually my approach (I don't want to remember the order of arguments). Either way, I don't think it matters too much.

2017-07-14 02:48 UTC, basheersubei commented on rollingshutter.py
> +    parser.add_argument('-x', '--extension-type', default='png', help='Speed variable to control how many rows to jump by per frame.')
woops

2019-09-09 19:43 UTC, closed without merging

2019-09-09 19:44 UTC, bsubei commented
closed due to inactivity